> 原则：
1. 初始情况
2. 往初始情况发展
3. 往初始情况发展的条件判断
4. 一定要在纸上提前画一画，分析几种情况
5. 问题转化

R-4.1 对于一个含有n个元素的序列S，描述一个递归算法查找其最大值。所给出的递归算法时间复杂度和可见复杂度各是多少？

In [128]:
def find_max(data, n):
    if n == 0:
        return data[0]
    else:
        m = find_max(data, n-1)
        return data[n] if data[n] > m else m

In [130]:
import numpy as np
if __name__ == '__main__':
    data = np.random.randint(0, 99, size=(100,))
    #data = sorted(list(data))
    print(data)
    result = find_max(data, len(data)-1)
    print(result)

[73 26 82 63 70 91 60 41 98  3 42 86 47 86 38  2 50 78 11 25 79 19 52 69
 17 84 25 94 35 27 45 46 93 87 60 24 16  8 92 35 62 57  4  4 49 71 21 79
 95 84 83 97 54 10  6 38 27 27 89 92 52 75 87 50 72 93 44 13 66 45 78 63
 33 16 77 17 84 17 35 60 25 90 50 81 80 11 49 51 28 81 75 39  0 84 15 40
  2 97 86 46]
98


In [132]:
import numpy as np
if __name__ == '__main__':
    for i in range(100):
        data = np.random.randint(0, 99, size=(100,))
        result = find_max(data, len(data)-1)
        if result != max(data):
            print("计算错误")
        # print(result==max(data))

R-4.2 使用在代码段4-11中实现的传统函数，绘制出power(2, 5)函数计算的递归跟踪。

略

R-4.3 如代码段4-12实现的函数所示，使用重复平方法绘制出power(2, 18)函数计算的递归跟踪。

略

R-4.4 绘制。。。

R-4.5 绘制。。。

R-4.6 描述一个递归函数，用于计算第n个调和数(harmonic number)，其中$H_{n}=\sum_{i=1}^{n}1/i$。

In [49]:
def harmonic(n):
    if n == 1:
        return 1
    else:
        return 1/n + harmonic(n-1)

In [50]:
if __name__ == '__main__':
    result = harmonic(10)
    print(result)

2.9289682539682538


R-4.7 描述一个递归函数，它可以把一串数字转换成对应的整数。例如，'13531'对应的整数为13531。

In [63]:
def transform(string, n):
    if n == 0:
        return int(string[0]) * (10**(len(string)-1))
    else:
        return int(string[n])*(10**(len(string)-n-1)) + transform(string, n-1)

In [68]:
if __name__ == '__main__':
    string = '12345678987654321'
    result = transform(string, len(string)-1)
    print(result)

12345678987654321


R-4.8 Islabel...

C-4.9 写一个简短的递归函数，用于在不使用任何循环的条件下查找一个序列的最小值和最大值。

In [141]:
def find_min_max(data, n):
    if n == 0:
        return data[0], data[0]
    else:
        m1, m2 = find_min_max(data, n-1)
        return ((data[n] if data[n] < m1 else m1), (data[n] if data[n] > m2 else m2))

In [142]:
import numpy as np
if __name__ == '__main__':
    data = np.random.randint(0, 99, size=(100,))
    data = sorted(list(data))
    print(data)
    result = find_min_max(data, len(data)-1)
    print(result)

[0, 2, 3, 3, 3, 4, 4, 4, 4, 5, 6, 6, 7, 8, 9, 10, 11, 12, 13, 16, 16, 17, 17, 18, 20, 21, 21, 21, 22, 23, 23, 23, 24, 26, 29, 30, 30, 30, 31, 31, 32, 32, 32, 32, 33, 34, 34, 35, 35, 37, 37, 37, 39, 39, 44, 46, 46, 48, 48, 49, 49, 50, 51, 51, 55, 56, 57, 59, 59, 60, 61, 63, 64, 67, 68, 70, 70, 71, 71, 71, 72, 73, 73, 73, 73, 74, 77, 78, 82, 82, 84, 85, 89, 91, 91, 92, 96, 96, 98, 98]
(0, 98)


In [145]:
import numpy as np
if __name__ == '__main__':
    for i in range(100):
        data = np.random.randint(0, 99, size=(100,))
        result = find_min_max(data, len(data)-1)
        if result[0]!=min(data) or result[1]!=max(data):
            print("计算错误")
        # print(result==max(data))

C-4.10 在只使用加法和整数除法的情况下，描述一个递归算法，来计算以2为底的n的对数的整数部分。

In [184]:
def log2(n):
    if n < 2:
        return 0
    else:
        n = n // 2
        return 1 + log2(n)

In [188]:
print(log2(10))

3


In [189]:
import numpy as np

for i in range(1, 100):
    if log2(i) != int(np.log2(i)):
        print('计算错误')

In [190]:
def log2(n):
    sum = 0
    while 1:
        if n < 2:
            break
        n = n // 2
        sum += 1
    return sum

In [181]:
print(log2(2))

1


C-4.11 描述一个有效的递归函数来求解元素的唯一性问题，在不使用排序的最坏的情况下运行时间最多是$O(n^2)$。

In [31]:
# 2020-12-30 10：14
def unique(data, n):
    if n == 0:                          # 基本情况
        return True
    else:
        if data[n] == data[n-1]:        # 条件判断
            return False
        else:
            return unique(data, n-1)    # 往基本情况靠近

In [32]:
# 正确算法
def unique2(S):
    """Return True if there are no duplicate elements in sequence S."""
    temp = sorted(S)    # create a sorted copy of S
    for j in range(1, len(temp)):
        if temp[j-1] == temp[j]:
            return False    # found duplicate pair
    return True             # if we reach this, elements wew unique

In [33]:
if __name__ == '__main__':
    import numpy as np
    for i in range(100):
        data = np.random.randint(0, 9, size=(100,))
        if unique(data, len(data)-1) == unique2(data):
            pass
        else:
            print("计算错误")

C-4.12 在只使用加法和减法的情况下，给出一个递归算法，来计算两个正整数m和n的乘积。

$$ f(x)=\left\{
\begin{aligned}
x & = & \cos(t) \\
y & = & \sin(t) \\
z & = & \frac xy
\end{aligned}
\right.
$$

In [48]:
def product(n, m):
    if m == 1:
        return n
    else:
        return n + product(n, m-1)

In [50]:
import random


if __name__ == '__main__':
    for i in range(100):
        m, n = random.randint(0, 99), random.randint(0, 99)
        if product(n, m) == m*n:
            #print("计算正确")
            pass
        else:
            print("计算错误")

C-4.13 在4.2节中，。。。。

C-4.14 汉诺塔问题

C-4.15 编写一个递归函数，该函数输出一个含有n个元素的集合的所有子集（没有任何重复的子集）。

In [58]:
def maximal_subset(data):
    if len(data) == 0:    # 如果data为空，返回空列表
        return [[]]
    
    subsets = []
    first_element = data[0]
    remaining_list = data[1:]
    
    for subset in maximal_subset(remaining_list):
        subsets.append(subset)
        next_subset = subset + [first_element]
        subsets.append(next_subset)
    return subsets

In [60]:
data = ['a', 'b', 'c']
print(maximal_subset(data))

[[], ['a'], ['b'], ['b', 'a'], ['c'], ['c', 'a'], ['c', 'b'], ['c', 'b', 'a']]


C-4.16 编写一个简短的递归Python函数，它接受一个字符串s并输出其逆置字符串。例如字符串'pots%pans'的逆置字符串为'snap&stop'。

In [77]:
def reverse_string(string, n):
    if n == 0:
        return string[0]
    else:
        return string[n] + reverse_string(string, n-1)

In [79]:
string = 'pots%pans'
print(reverse_string(string, len(string)-1))

snap%stop


In [81]:
string = '1234567'
print(reverse_string(string, len(string)-1))

7654321


C-4.17 编写一个简短的递归Python函数，确定一个字符串s是否是它的一个回文字符串，也就是说，该字符串与其逆置字符串相同，例如，字符串'racecar'和'gohangasalamiimalasagnahog'是回文字符串。

In [15]:
def is_palindrome_string(data, start, stop):
    if stop - start == 1:
        return True
    elif stop - start == 2:
        return data[start] == data[start+1]
    else:
        if data[start] == data[stop]:
            return is_palindrome_string(data, start+1, stop-1)
        else:
            return False

In [17]:
def is_palindrome_string(data, start, stop):
    if stop == start:
        return True
    elif stop - start == 1:
        return data[start] == data[stop]
    else:
        if data[start] == data[stop]:
            return is_palindrome_string(data, start+1, stop-1)
        else:
            return False

In [20]:
string_1 = 'racecar'
print(is_palindrome_string(string_1, 0, len(string_1)-1))

string_2 = 'gohangasalamiimalasagnahog'
print(is_palindrome_string(string_2, 0, len(string_2)-1))

True
True


In [113]:
# 2020 12 30 19：15
def is_palindrome_string(data, start, stop):
    if start == stop:    # 奇数个
        return True
    elif stop - start == 1:   # 偶数个
        return data[start] == data[stop]
    else:
        if data[start] != data[stop]:
            return False
        else:
            return is_palindrome_string(data, start+1, stop-1)

In [114]:
string_1 = 'racecar'
print(is_palindrome_string(string_1, 0, len(string_1)-1))

string_2 = 'gohangasalamiimalasagnahog'
print(is_palindrome_string(string_2, 0, len(string_2)-1))

string_3 = 'abc'
print(is_palindrome_string(string_3, 0, len(string_3)-1))

string_4 = 'aba'
print(is_palindrome_string(string_4, 0, len(string_4)-1))

True
True
False
True


C-4.18 使用递归编写一个Python函数，确定字符串s中是否元音字母比辅音字母多。

In [68]:
vowels = ['a', 'e', 'i', 'o', 'u']
consonants = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't',  'v', 'w', 'x', 'y', 'z']

In [69]:
# 非递归版本
# 返回直接结果
def compare(data):
    vowel_count, consonant_count = 0, 0
    for val in data:
        if val in vowels:
            vowel_count += 1
        else:
            consonant_count += 1
    return vowel_count > consonant_count

In [70]:
# 非递归版本
# 直接返回数目
def compare(data):
    count = 0
    for val in data:
        if val in vowels:
           count += 1
    return count

In [71]:
print(compare('abc'))

1


In [72]:
def compare(data, n):
    if n == 0:
        return 1 if data[n] in vowels else 0
    else:
        return 1+compare(data, n-1) if data[n] in vowels else compare(data, n-1)
    
def get_result(data):
    count = compare(data, len(data)-1)
    return count > len(data) - count

In [75]:
data = 'aeiou'
data= 'ae123'
print(compare(data, len(data)-1))
print(get_result(data))

2
False


C-4.19 编写一个简短的递归Python函数，用于重新排列一个整数值序列，使得所有偶数值出现在所有奇数值的前面。

> 问题转化：有条件的二路递归。

In [119]:
# 非递归版本

def organize_recurse_not(data):
    odd = []
    even = []
    for val in data:
        if val % 2 == 0:
            even.append(val)
        else:
            odd.append(val)
    return even + odd

In [120]:
import numpy as np
data = np.random.randint(0, 9, size=(10,))
print(data)
print(organize_recurse_not(data))

[7 2 8 0 1 8 0 1 6 0]
[2, 8, 0, 8, 0, 6, 0, 7, 1, 1]


In [143]:
def organize_recurse(data, n):
    if n == 0:
        return [data[0]]
    else:
        if data[n] % 2 == 0:
            return [data[n]] + organize_recurse(data, n-1)
        else:
            return organize_recurse(data, n-1) + [data[n]]

In [144]:
import numpy as np
data_ = np.random.randint(0, 9, size=(10,))
print(data)
print(organize_recurse(data_, len(data_)-1))

[7 2 8 0 1 8 0 1 6 0]
[6, 8, 4, 4, 8, 2, 1, 5, 7, 7]


C-4.20 给定一个未排序的整数序列S和整数k，描述一个递归算法，用于对S中的元素重新排序，使得所有小于等于k的元素在所有大于k的元素之前。在这个含有n个值得序列中，算法的时间复杂度是多少？

In [146]:
def sort(data, target, n):
    if n == 0:
        return [data[n]]
    else:
        if data[n] <= target:
            return [data[n]] + sort(data, target, n-1)
        else:
            return sort(data, target, n-1) + [data[n]]

In [160]:
import numpy as np
import random
data = np.random.randint(0, 9, size=(10))
print(data)
target = random.randint(0, 9)
print(target)
result = sort(data, target, len(data)-1)
print(result)

[4 2 3 2 6 4 3 6 2 7]
3
[2, 3, 2, 3, 2, 4, 6, 4, 6, 7]


C-4.21 假设给出一个含有n个元素的序列S，这个序列是包含不同元素的升序序列。给定一个数k，描述一个递归算法找到S中总和为k的两个整数（如果这样的一对整数存在）。算法的时间复杂度是多少？

In [19]:
# 非递归解法
# 时间复杂度为O(n)
# 但是没有利用升序的条件
# 没有返回坐标
def find_pair(data, target):
    enum = enumerate(data)
    for i, val in enum:
        if target - val in data:
            return val, target-val
    return -1, -1

In [ ]:
# 非递归解法
# 时间复杂度为O(n)
# 但是没有利用升序的条件
# 返回坐标
def find_pair(data, target):
    hashtable = dict()
    for i in range(len(data)):
        if target-data[i] in hashtable:
            return [hashtable[target-data[i]], i]
        hashtable[data[i]] = i
    return []

In [45]:
# 使用hash表，查找复杂度为O(1)
# 时间复杂度为O(n)
def find_pair(data, target):
    hashtable = dict()
    for i, val in enumerate(data):
        if target-val in hashtable:
            return [hashtable[target-val], i]
        hashtable[val] = i
    return []

In [65]:
# 递归解法
# 利用升序条件
# 可以自然而言的想到使用二分法
def find_pair(data, i, j, k):
    if i == j:
        return False
    elif data[i] + data[j] < k:
        return find_pair(data, i+1, j, k)
    elif data[i] + data[j] > k:
        return find_pair(data, i, j-1, k)
    else:
        return True

In [88]:
# 递归解法
# 利用升序条件
# 可以自然而言的想到使用二分法
# 但是如何实现
def find_pair(data, i, j, k):
    if i == j:
        return False
    elif data[i] + data[j] < k:
        return find_pair(data, i+1, j, k)
    else:
        if data[i] + data[j] > k:
            return find_pair(data, i, j-1, k)
        else:
            return True

In [125]:
import numpy as np
import random
data = np.random.randint(0, 9, size=(10))
# 排序
data = sorted(data)
target = random.randint(0, 9)
result = find_pair(data, 0, len(data)-1, target)
print(data)
print(target)
print(result)

[1, 2, 3, 4, 5, 6, 7, 7, 8, 8]
2
False


C-4.22 从代码段4-12使用重复平方的power函数的版本中，实现一个非递归版本。

In [6]:
def power(x, n):
    result = 1
    for i in range(n):
        result *= x
    return result

In [4]:
def power(x, n):
    result = 1
    i = 1
    while i <= n:
        result *= x
        i +=1
    return result

In [7]:
for i in range(1,5):
    print(power(i, i), i**i)

1 1
4 4
27 27
256 256


In [12]:
def power(x, n):
    k = 0
    while (1 << k) <= n:
        k += 1
    answer = 1.0
    for j in range(k-1, 1, 1):
        answer *= answer
        if (1 << j) & n > 0:
            answer *= x
    return answer

In [13]:
for i in range(1,5):
    print(power(i, i), i**i)

1.0 1
1.0 4
1.0 27
1.0 256
